### ISSUE TITLE
Missing ./public folder

### ISSUE THREAD

**Issue by davedawkins** [HarryMcCarney/ProductAdoptionSim#1]
Did you forget to add it to the repo?

**Comment by HarryMcCarney** [comment]
publishing to docs so output can be served as github page. Vey hacky and had to manually copy it over. Presumably fable allows you to set output folder for build commands. Couldnt find much about this online.

**Comment by HarryMcCarney** [comment]
the build cmd which publishes to docs should probably be in a github action

**Comment by davedawkins** [comment]
Oh I see. I missed that.

webpack handles all that.
```js

module.exports = {
    mode: "development",
    entry: "./src/App/App.fs.js",
    output: {
        path: path.join(__dirname, "./public"),
        filename: "bundle.js",
    },
    devServer: {
        publicPath: "/",
        contentBase: "./public",
        port: 8080,
    },
}
```

The way I've seen it done in other repos is to use `./public` as per the templates and other examples, and then to publish to the docs folder on the gh-pages branch. 

Grab this file from Sutil, which I originally grabbed from either a Zaid or Maxime repo:

https://github.com/davedawkins/Sutil/blob/main/publish.js

Invoked like this:

```shell
npm install gh-pages
node publish.js
```

**Comment by HarryMcCarney** [comment]
Great thanks, thats implemented and seems to work. Nice neat way to publish!
